name: Player API Lambda

on:
  workflow_dispatch: # Enables manual triggering
  push:
    paths:
      - 'prototypes/**'

jobs:
  build-and-deploy:
    name: Build and Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    # Step 3: Build the Go binary
    - name: Build Go binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o main main.go
      working-directory: ./prototypes/services/player_service
      env:
        GO111MODULE: auto
        GOPROXY: https://proxy.golang.org
        GOSUMDB: sum.golang.org
        CGO_ENABLED: 0

    # Step 4: Package the binary into a ZIP file
    - name: Package Lambda function
      run: zip player_service.zip main

    # Step 5: Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Update Lambda Function Code
      run: |
        aws lambda update-function-code \
          --function-name ctf-player-service \
          --zip-file fileb://player_service.zip