name: Provision AWS with Terraform

on:
  workflow_dispatch: # Enables manual triggering
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest

    # determines AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, 
    # refer to github environment 
    environment: development 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_TERRAFORM_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_TERRAFORM_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/TerraformExecutionRole
        role-session-name: GitHubActionsTerraformApply

    - name: Restore Terraform Cache
      uses: actions/cache@v3
      with:
        path: terraform/.terraform
        key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          terraform-${{ runner.os }}-

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5 # Specify the Terraform version you want to use

    - name: Terraform Init (if cache is missing)
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan 
      
    - name: Terraform Apply
      if: ${{ success() }}
      working-directory: terraform
      run: terraform apply -auto-approve tfplan
